### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ematte** [ematte/react-movie-app#1]
- [ ] add font awesome
- [ ] add link to movie's website
- [ ] add selection between grid and list view
- [ ] add search results pagination
- [ ] further split some components
